version: '3.8'
name: development
services:
  algorithms:
    container_name: algorithms
    image: anicmarko9/algorithms:1.0
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
networks:
  dev:
    name: dev
